language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

addons:
  sonarcloud:
    organization: "grgk-github"

script:
  - vendor/bin/phpunit --coverage-clover build/logs/phpunit/clover.xml --log-junit build/logs/phpunit/junit.xml --coverage-xml build/logs/phpunit/coverage/xml --coverage-html build/logs/phpunit/coverage/html
  - sonar-scanner

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
